-- DATEV exports are immutable server-generated byte snapshots. Existing
-- metadata-only rows remain readable, while all new exports persist bytes.
ALTER TABLE datev_exports ADD COLUMN IF NOT EXISTS content_bytes BYTEA;

CREATE OR REPLACE FUNCTION billme_protect_datev_export_bytes() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION 'DATEV export snapshots are immutable';
  END IF;
  IF OLD.content_bytes IS DISTINCT FROM NEW.content_bytes
     OR OLD.file_path IS DISTINCT FROM NEW.file_path
     OR OLD.meta_json IS DISTINCT FROM NEW.meta_json
     OR OLD.record_count IS DISTINCT FROM NEW.record_count
     OR OLD.from_date IS DISTINCT FROM NEW.from_date
     OR OLD.to_date IS DISTINCT FROM NEW.to_date THEN
    RAISE EXCEPTION 'DATEV export snapshots are immutable';
  END IF;
  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS datev_exports_immutable ON datev_exports;
CREATE TRIGGER datev_exports_immutable BEFORE UPDATE OR DELETE ON datev_exports FOR EACH ROW EXECUTE FUNCTION billme_protect_datev_export_bytes();
